[project]
name = "ai-elements-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.9.0",
    "fastapi[standard]>=0.124.2",
    "langchain-google-genai>=4.0.0",
    "langfuse>=3.0.0",
    "litellm>=1.80.11",
    "llama-index-llms-google-genai==0.8.3",
    "llama-index-llms-openai==0.6.12",
    "llama-index-workflows>=2.11.6",
    "openinference-instrumentation-llama-index>=4.3.9",
    "opentelemetry-api>=1.39.1",
    "opentelemetry-exporter-otlp>=1.39.1",
    "opentelemetry-sdk>=1.39.1",
    "python-dotenv>=1.2.1",
    "python-socketio[asyncio-client]>=5.11.0",
    "rich>=14.2.0",
]
